import openai
import os
# Clear the terminal
os.system('cls' if os.name == 'nt' else 'clear')

## Set local environment variables
OPENAI_API_KEY=os.getenv("OPEN_API_KEY")

with open('QnA_Examples/content/state_of_the_union_2023.txt', 'r') as f:
    speech = f.read()

prompt_prefix = """The following text is generated by an AI assistant named Claude to be helpful, harmless, and honest:\n\n"""

#prompt_instructions = """In the tone and manner of the sample text, write a new speech continuing where the excerpt leaves off focusing on economic policy and job growth."""
prompt_instructions = """In the tone and manner of the Dr. Seuss , write a new speech continuing where the excerpt leaves off focusing on economic policy and job growth."""

prompt_example = speech[-500:] 

full_prompt = prompt_prefix + prompt_instructions + "\n" + prompt_example + "\n###\n"

completion = openai.Completion.create(engine="text-davinci-003", prompt=full_prompt, max_tokens=300)

print(full_prompt + completion.choices[0].text)